expname: dense_rainforest_understory_outside
num_dreams: 0
phase5:
  render_settings:
    min_near_plane: 0.001
    keep_ratio: 1.0
    width: 1920
    height: 1080
  custom_trajectory:
    enable: true
    eqr_resolution:
      width: 4096
      height: 2048
    positions:
    - - 1.57
      - -10.0
      - 3.0
      - -15
      - 90
    render_eqr_too: false
  custom_world:
    enable: true
    scene_type: sphericaldreamer
    world_path: /home/a.schnepf/phd/experiments/dense_rainforest_understory/sphericaldreamer/pcd.ply
    scale_factor: 1.0
  nfs_dataset:
    fov_deg: 54.2
    bg_color:
    - 0
    - 0
    - 0
    - 0
save_dir: OUTPUTS/X_ICML_RENDERS/outside
