expname: Cityscape
prompt: A dense urban environment filled with tall buildings, interconnected streets, public squares, and layered infrastructure, alive with movement, lights, and architectural variety.

load_phase1a_from: null
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null
load_phase3_from: null #TODO: implemtement this



save_dir: OUTPUTS/SphericalDreamerRecurse/_exp1