# ---meta---
expname: C1_city_corr
load_phase1_from: C0_city

# ----- args generation -----
prompt: A bustling city street at night, neon lights reflecting on wet pavement, realism style.

geometry_correction:
  sphere:
    correct_depth: False
    near: 0.1
    far: 1.0
    correct_walls: True
    correct_floor: True
    depth_threshold_for_floor_correction: 0.6
    remove_sky: False
    remove_outliers: True
    verbose: False
    plot: False