expname: Caverns_dilate_hblend_mask
prompt: A vast subterranean environment of winding tunnels, towering rock formations, echoing chambers, and glowing mineral deposits, shaped by water and geological forces.

load_phase1a_from: Caverns
load_phase1b_from: Caverns
load_phase2a_from: Caverns
load_phase2b_from: Caverns
load_phase2c_from: null
load_phase3_from: null #TODO: implemtement this