expname: Volcanic
prompt: A harsh volcanic environment shaped by intense geological activity, featuring jagged rock formations, hardened lava flows, ash-covered ground, and glowing fissures in the earth.

load_phase1a_from: Volcanic
load_phase1b_from: Volcanic
load_phase2a_from: Volcanic
load_phase2b_from: Volcanic
load_phase2c_from: Volcanic
load_phase3_from: null #TODO: implemtement this