# ---meta---
expname: forest_v3

load_phase1a_from: null
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null

# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 2
pcd_upsampling_factor: 4


phase2: # pairs of sphere inpainting + deformation
  outliers_removal: 
    apply_on_fg: True
    apply_on_ldi: False
    options:
      nb_neighbors: 20
      std_ratio: 1.8
      verbose: True

phase5v2:
  render_settings:
    use_gpu_series: True   
    use_gpu_parallel: True 
    keep_ratio: 1 # is ignored if <1 and voxel_size is not None # TODO TEMP
  nfs_dataset:
    bg_color: [0, 0, 0, 1]
    fov_deg: 60.0
    nb_points: 1000
    nb_samples_per_point: 5
    ranges:
      min_x: 0.0
      min_y: -0.2
      max_y: 0.2
      min_z: -0.1
      max_z: 0.3
  custom_trajectory: # Render custom cameras # TODO TEMP
    enable: true
    render_eqr_too: true
    positions: [
      [0, -0.15, 0, 0, 270],
      [0, -0.1, 0, 0, 270],
      [0, -0.05, 0, 0, 270],
      [0, 0, 0, 0, 270],
      [0, 0.05, 0, 0, 270],
      [0, 0.1, 0, 0, 270],
      [0, 0.15, 0, 0, 270],
    ] # List of [x, y, z, elev, azim]
  custom_world: # Override the default world point cloud # TODO TEMP
    enable: True
    scale_factor: 1.3 
    world_path: OUTPUTS/test_mesh.obj
    # world_path: OUTPUTS/teddy.obj