# ---meta---
expname: F1_forest

# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 5

# load_phase1_from: 4_forest
# load_phase2a_from: 3_forest
# load_phase2b_from: 3_forest
# load_phase3_from: 3_forest
  

phase4: # render video
  point_size: 5.0
  fix_world: True
  render_settings:
    trajectory: walk # in ['walk', 'walk_look', 'walk_lookaround', 'zigzag', 'walk_lookupdown', 'custom']
    framerate:
      fps: 15
      fpm: 10
      fpd_e: 1
      fpd_a: 1
  world:
    correct_depth: False
  remove_outliers:
    apply: True
