# ---meta---
expname: debug

# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 2
pcd_upsampling_factor: 2