# ---meta---
expname: debug_upsampling=4
load_phase1a_from: debug_upsampling=4
load_phase1a_from: debug_upsampling=4
load_phase1b_from: debug_upsampling=4
load_phase2a_from: debug_upsampling=4
load_phase2b_from: debug_upsampling=4
load_phase2c_from: debug_upsampling=4
# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 2
pcd_upsampling_factor: 4