# ---meta---
expname: F3_no_sph_outlier_removal

# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 5

load_phase1_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase3_from: null

geometry_correction:
  sphere:
    remove_outliers: False


phase4: # render video
  world:
    correct_depth: False
    correct_walls: True