expname: phantom_opera_cave_river
num_dreams: 0
phase5:
  render_settings:
    min_near_plane: 0.001
    keep_ratio: 1.0
    point_size: 0.033
  custom_trajectory:
    enable: true
    eqr_resolution:
      width: 2048
      height: 1024
    positions:
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 90
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 180
    - - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 270
    - - -0.1875
      - 0.0
      - 0.0
      - 0.0
      - 0
    - - -0.1875
      - 0.0
      - 0.0
      - 0.0
      - 90
    - - -0.1875
      - 0.0
      - 0.0
      - 0.0
      - 180
    - - -0.1875
      - 0.0
      - 0.0
      - 0.0
      - 270
    - - -0.375
      - 0.0
      - 0.0
      - 0.0
      - 0
    - - -0.375
      - 0.0
      - 0.0
      - 0.0
      - 90
    - - -0.375
      - 0.0
      - 0.0
      - 0.0
      - 180
    - - -0.375
      - 0.0
      - 0.0
      - 0.0
      - 270
    render_eqr_too: true
  custom_world:
    enable: true
    scene_type: wonderjourney
    world_path: /home/a.schnepf/phd/experiments/phantom_opera_cave_river/wonderjourney/pcd.ply
    scale_factor: 1.0
  nfs_dataset:
    fov_deg: 54.2
save_dir: OUTPUTS/X_ICML_RENDERS/qualitative
