# ---meta---
expname: Forest

load_phase1a_from: null
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null

# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 5
pcd_upsampling_factor: 4


phase2: # pairs of sphere inpainting + deformation
  outliers_removal: 
    apply_on_fg: True
    apply_on_ldi: False
    options:
      nb_neighbors: 20
      std_ratio: 1.8
      verbose: True
      
  excessive_pcd_logging: True


ldi: # layered depth image
  depth_inpainting:
    additionnal_mask_dilation_px: 15