# ---meta---
expname: sky_only

# ----- args generation -----
prompt: Only the sky, full 360 degree panoramic view, no ground, no objects, just clouds and blue sky.

num_dreams: 2
pcd_upsampling_factor: 2



phase4: # render video
  exclude_sky_points: True 