"A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.",
        "A wide panoramic landscape with a bright blue sky, majestic mountains in the background, a calm turquoise sea in the foreground, and lush greenery along the shore. The scene should feel vibrant, sunny, and relaxing, like a holiday postcard photograph, with realistic lighting and high detail.",
        "A bustling city street at night, neon lights reflecting on wet pavement, realism style.",
        # "Sandy beach, large driftwood in the foreground, calm sea beyond, realism style.",
        # "A realistic illustration of a college campus. In the middle ground, several academic buildings with brick facades and large windows stand prominently. In the background, a bright blue sky with scattered clouds stretches across the scene. In the foreground, a few elements commonly found on campus, such as students walking, bicycles parked along a path, and a grassy lawn with trees, add depth and life to the scene.",
        # "A wide field under daylight, covered in lush green grass with worn paths where the grass has been trampled by many footsteps. In the center of the field stands a large concert stage, decorated with bold triangular patterns. On the stage rests a single guitar, but no performers are present. In front of the stage, a lively crowd gathers, waiting for the show to begin."


        "33_forest",
        "33_seaside",
        "33_city",

# skip_phase1 = True
    # skip_phase2 = False
    # skip_phase3 = True
    # skip_phase2_inpainting = True
    # skip_phase3_inpainting= False
    # save_dir = "OUTPUTS/SphericalDreamerRecurse"

    # seeds = [119224, 119224+9, 119224+20, 119224+33, 119224+45]
    # prompts = [
    #     "A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.",
    #     "A wide panoramic landscape with a bright blue sky, majestic mountains in the background, a calm turquoise sea in the foreground, and lush greenery along the shore. The scene should feel vibrant, sunny, and relaxing, like a holiday postcard photograph, with realistic lighting and high detail.",
    #     "A bustling city street at night, neon lights reflecting on wet pavement, realism style.",
    #     # "Sandy beach, large driftwood in the foreground, calm sea beyond, realism style.",
    #     # "A realistic illustration of a college campus. In the middle ground, several academic buildings with brick facades and large windows stand prominently. In the background, a bright blue sky with scattered clouds stretches across the scene. In the foreground, a few elements commonly found on campus, such as students walking, bicycles parked along a path, and a grassy lawn with trees, add depth and life to the scene.",
    #     # "A wide field under daylight, covered in lush green grass with worn paths where the grass has been trampled by many footsteps. In the center of the field stands a large concert stage, decorated with bold triangular patterns. On the stage rests a single guitar, but no performers are present. In front of the stage, a lively crowd gathers, waiting for the show to begin."
    # ]
    # expnames=[
    #     "33_forest",
    #     "33_seaside",
    #     "33_city",
    # ]
    
    # # ----- args phase I -----
    # num_dreams = 4
    # override_with_inpaint=False
    # depth_model = "360mono"  # "360mono" or "egformer"
    # if depth_model == 'egformer':
    #     width = 1024
    #     height = 512
    # else:
    #     width = 1440
    #     height = 720

    # # ----- args PHASES II -----
    # sphere_radius = 1.0
    # FAR=1.0
    # NEAR=0.01
    # delta_walk = FAR * np.pi / 2
    # raise_intermediate_camera_by_z = 0.3    
    # pcd_upsampling_factor = 2 # int
    # translation_direction = my_utils.get_norm_vector(np.array([1, 0, 0], dtype=np.float32))
    # opening_kwargs = {
    #     'opening_mode': 'cut+cylinder',
    #     'delta_cut': 2*np.pi/3,
    # }
    # sphere_correction_kwargs = {
    #     "correct_depth": False,
    #     "near": NEAR,
    #     "far": FAR,
    #     "correct_walls": False,
    #     "correct_floor": False,
    #     "depth_threshold_for_floor_correction": 0.6,
    #     "remove_sky": False,
    #     "remove_outliers": True,
    #     "verbose": False,
    #     "plot": True,
    # }

    # # --- args PHASE III ---
    # world_correction_kwargs = {
    #     "correct_depth": False,
    #     "near": NEAR,
    #     "far": FAR,
    #     "correct_walls": False,
    #     "correct_floor": True,
    #     "depth_threshold_for_floor_correction": 1.0,
    #     "remove_outliers": False,
    # }
    # # --- end args ---