expname: phantom_opera_cave_river_outside
num_dreams: 0
phase5:
  render_settings:
    min_near_plane: 0.001
    keep_ratio: 1.0
    width: 1920
    height: 1080
    point_size: 0.0022
    save_rgba: true
  custom_trajectory:
    enable: true
    eqr_resolution:
      width: 4096
      height: 2048
    positions:
    - - 0.0
      - -0.3
      - 0.0
      - 0.0
      - 0.0
    render_eqr_too: true
  custom_world:
    enable: true
    scene_type: scenescape
    world_path: /home/a.schnepf/phd/experiments/phantom_opera_cave_river/scenescape/mesh.obj
    scale_factor: 1.0
  nfs_dataset:
    fov_deg: 54.2
    bg_color:
    - 0
    - 0
    - 0
    - 0
save_dir: OUTPUTS/X_ICML_RENDERS/outside
