expname: "insert_expname_here"
load_phase1a_from: null
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null
load_phase3_from: null
num_dreams: 2
prompt: "insert prompt here"
save_dir: OUTPUTS/SphericalDreamerRecurse/diversity
