# ---meta---
expname: default_expname
skip_phase3: True

load_phase1a_from: null
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null
load_phase3_from: null #TODO: implemtement this


# ----- main args  -----
num_dreams: 4
prompt: "default prompt"
width: 1440
height: 720
pcd_upsampling_factor: 4
translation_direction: [1, 0, 0] # x, y, z
delta_walk: 1.57
raise_intermediate_camera_by_z: 0.3    

geometry_correction:
  sphere:
    correct_depth: False
    near: 0.1
    far: 1.0
    correct_walls: False
    correct_floor: False
    depth_threshold_for_floor_correction: 0.6
    remove_sky: False
    verbose: False
    plot: False

world_opening:
  opening_mode: cut+cylinder
  delta_cut: 2.0943 # radians

ldi: # layered depth image
  masking:
    edges_detection:
      remove_depth_low_freq:
        apply: True
        method: gaussian # 'gaussian' or 'fourier'
        fourier:
          cutoff_frac: 0.01
        gaussian:
          sigma_v: 50.0
          sigma_h: 50.0
      canny:
        low_t: 35
        high_t: 90
      sobel:
        ksize: 3
      depth_sharpening:
        apply: False
        filter_size: 5          
        depth_threshold: 0.01   
        sigma_s: 3.0            
        sigma_r: 0.1            
    segmask_detection: # parameters for SAM mask generation
      points_per_side: 32 # was 16
      pred_iou_thresh: 0.5 
      stability_score_thresh: 0.6 
      crop_n_layers: 0
      crop_n_points_downscale_factor: 0
      min_mask_region_area: 20 
    segmask_scoring:
      score_threshold: 0.02
      max_edge_dist: 0 # tested 1: should be 0
      step_along_normal: 1.0
      min_pairs: 10 # was 30
  inpainting:
    mask_dilatation_px: 10
    strength: 0.6
    flux_inpainting_resolution: 
      height: 1024
      width: 2048
    lama_inpainting_resolution: 
      height: 512
      width: 1024
  depth_inpainting:
    method: bilinear_plus_nn # 'harmonic_blending', 'infusion', 'nearest' or 'bilinear_plus_nn'
    additionnal_mask_dilation_px: 0
    fill_holes: True
    pad_width: 150
    apply_post_processing: True
  save_plots: True
  
phase1: # panorama generation
  override_with_inpaint: False
  apply_ldi: True 
  outliers_removal: 
    apply_on_fg: True
    apply_on_ldi: False
    options:
      nb_neighbors: 20
      std_ratio: 1.7 # increase to remove fewer points
      verbose: True

phase2: # pairs of sphere inpainting + deformation
  apply_ldi: True
  rendering_version: 0 # 0, 1 or 2
  skip_inpainting: False
  inpainting_resolution:
    height: 1024
    width: 2048
  inpainting_blend_mode: compose # 'compose' or 'seamless' # seamless fails on some images. Use compose.
  rotate_intermediate_camera_by_deg: 0.0
  outliers_removal: 
    apply_on_fg: True
    apply_on_ldi: False
    options:
      nb_neighbors: 20
      std_ratio: 2.1 # increase to remove fewer points
      verbose: True
  excessive_pcd_logging: False

phase3: # world geometry correction
  pointcloud_downsampling:
    mode: "auto" # in ['deactivated', 'auto', 'voxel', 'skip']
    skip_options:
      stride: 10
    voxel_options:
      voxel_size: 0.01
    auto_options:
      num_max_points: 50e6

  world_correction:
    apply: True
    options:
      correct_depth: False
      near: 0.1
      far: 1.0
      correct_walls: False
      correct_floor: True
      depth_threshold_for_floor_correction: 1.0

  remove_outliers:
    apply: False # all outliers should have been already removed in phase1 and phase2
    options:
      nb_neighbors: 20
      std_ratio: 5.0

phase4: # render video
  visualize_removed_points: False
  point_size: 3.0
  bg_color: [0, 0, 0, 1]
  width: 512
  height: 512

  render_settings:
    trajectory: walk_lookaround # in ['walk', 'walk_look', 'walk_lookaround', 'zigzag', 'walk_lookupdown', 'custom']
    custom_trajectory: [] # List of [x, y, z, elev, azim], only used if trajectory is 'custom'
    ranges:
      min_x: 0.0
      min_y: -1.0
      max_y: 1.0
      min_z: -0.1
      mid_z: 0.1
      max_z: 1.5
    framerate:
      fps: 60
      fpm: 60
      fpd_e: 1
      fpd_a: 1

phase5: # render nfs dataset
  visualize_removed_points: False
  fix_world: True
  point_size: 3.0
  bg_color: [0, 0, 0, 1]
  width: 512
  height: 512
  remove_outliers:
    apply: True
    nb_neighbors: 20
    std_ratio: 5.0
  world:
    correct_depth: False
    near: 0.1
    far: 1.0
    correct_walls: False
    correct_floor: True
    depth_threshold_for_floor_correction: 1.0
    remove_outliers: False
  render_settings:
    nb_points: 500
    nb_samples_per_point: 10
    ranges: 
      min_x: 0.0
      min_y: -0.2
      max_y: 0.2
      min_z: -0.1
      max_z: 0.3

phase6: # train splatfacto
  near_plane: 0.08
  far_plane: 86.0
  background_color: black


# tuned args
depth_model: 360mono # in ['360mono', 'egformer']
sphere_radius: 1.0

# seeding
seed: 119224
seed_offsets: [0, 9, 20, 33, 45]

# logging
save_dir: OUTPUTS/SphericalDreamerRecurse

