# ---meta---
expname: 0_city_rot90
skip_phase1: True

# ----- args generation -----
prompt: A bustling city street at night, neon lights reflecting on wet pavement, realism style.

phase2: 
  rotate_intermediate_camera_by_deg: 90.0


