# ---meta---
expname: debug_no_ldi_no_hblend
load_phase1a_from: debug_no_ldi
load_phase1b_from: debug_no_ldi
load_phase2a_from: debug_no_ldi
load_phase2b_from: debug_no_ldi
load_phase2c_from: null
load_phase3_from: null #TODO: implemtement this


# ----- args generation -----
prompt: An endless arid environment of rolling sand dunes and cracked earth, shaped by wind and heat, with sparse vegetation, intense sunlight, and a vast open sky.

num_dreams: 2
pcd_upsampling_factor: 2

phase1:
  apply_ldi: False
  
phase2:
  apply_ldi: False
  ablate_hblending:
    apply: True
    depth_blending_mode: "inpaint"
