# ---meta---
expname: debug
load_phase1a_from: debug
load_phase1b_from: debug
load_phase2a_from: debug
load_phase2b_from: debug

# ----- args generation -----
prompt: An endless arid environment of rolling sand dunes and cracked earth, shaped by wind and heat, with sparse vegetation, intense sunlight, and a vast open sky.

num_dreams: 2
pcd_upsampling_factor: 2


