# ---meta---
expname: debug_no_ldi

# ----- args generation -----
prompt: An endless arid environment of rolling sand dunes and cracked earth, shaped by wind and heat, with sparse vegetation, intense sunlight, and a vast open sky.

num_dreams: 2
pcd_upsampling_factor: 2

phase1:
  apply_ldi: False
  
phase2:
  apply_ldi: False
