# ---meta---
expname: Forest_ABL_ldi

load_phase1a_from: Forest
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null

# ----- args generation -----
prompt: A serene forest scene with a small stream, dappled sunlight filtering through the leaves, realism style.

num_dreams: 5
pcd_upsampling_factor: 4


phase1:
  apply_ldi: False
  
phase2:
  apply_ldi: False
