#!/bin/bash
# Run multiple experiments for SphericalDreamer

repo_dir="/home/a.schnepf/phd/SphericalDreamer"


# Define array of configs
configs_p2=(
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/japanese_onsen_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/japanese_onsen_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/japanese_onsen_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/soviet_metro_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/soviet_metro_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/soviet_metro_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/gothic_cathedral_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/gothic_cathedral_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/gothic_cathedral_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/cyberpunk_market_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/cyberpunk_market_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/cyberpunk_market_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/nautilus_shell_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/nautilus_shell_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/nautilus_shell_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/victorian_conservatory_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/victorian_conservatory_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/victorian_conservatory_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/cloud_monastery_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/cloud_monastery_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/cloud_monastery_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/artdeco_ballroom_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/artdeco_ballroom_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/artdeco_ballroom_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/roman_bathhouse_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/roman_bathhouse_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/roman_bathhouse_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pharaoh_tomb_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pharaoh_tomb_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pharaoh_tomb_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/ottoman_hammam_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/ottoman_hammam_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/ottoman_hammam_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/aztec_temple_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/aztec_temple_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/aztec_temple_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/alchemist_workshop_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/alchemist_workshop_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/alchemist_workshop_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/ming_throne_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/ming_throne_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/ming_throne_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/viking_longhouse_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/viking_longhouse_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/viking_longhouse_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/moorish_palace_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/moorish_palace_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/moorish_palace_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/byzantine_cistern_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/byzantine_cistern_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/byzantine_cistern_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pompeii_villa_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pompeii_villa_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pompeii_villa_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/baroque_opera_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/baroque_opera_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/baroque_opera_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/steel_mill_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/steel_mill_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/steel_mill_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/retro_diner_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/retro_diner_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/retro_diner_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/nuclear_bunker_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/nuclear_bunker_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/nuclear_bunker_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/soviet_submarine_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/soviet_submarine_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/soviet_submarine_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/artnouveau_metro_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/artnouveau_metro_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/artnouveau_metro_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/brutalist_pool_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/brutalist_pool_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/brutalist_pool_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/movie_palace_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/movie_palace_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/movie_palace_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/victorian_brewery_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/victorian_brewery_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/victorian_brewery_s2.yaml"
)

# Run experiments
for config in "${configs_p2[@]}"; do
    echo "🚀 Running experiment with config: $config"
    bash dream.sh $config

    if [ $? -ne 0 ]; then
        echo "❌ Experiment with config $config failed."
    fi

    echo "✅ Experiment with config $config completed successfully."
done

echo "🎉 All experiments completed successfully."