#!/bin/bash
# Run multiple experiments for SphericalDreamer

repo_dir="/home/a.schnepf/phd/SphericalDreamer"


configs_p1=(
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/psychiatric_ward_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/psychiatric_ward_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/psychiatric_ward_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/mission_control_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/mission_control_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/mission_control_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/venice_canal_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/venice_canal_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/venice_canal_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/moroccan_medina_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/moroccan_medina_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/moroccan_medina_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/havana_street_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/havana_street_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/havana_street_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/kowloon_slum_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/kowloon_slum_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/kowloon_slum_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/london_alley_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/london_alley_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/london_alley_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/tokyo_subway_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/tokyo_subway_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/tokyo_subway_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/mumbai_chawl_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/mumbai_chawl_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/mumbai_chawl_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/seoul_backstreet_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/seoul_backstreet_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/seoul_backstreet_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/detroit_factory_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/detroit_factory_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/detroit_factory_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/hongkong_scaffolding_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/hongkong_scaffolding_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/hongkong_scaffolding_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/space_station_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/space_station_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/space_station_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/asteroid_bazaar_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/asteroid_bazaar_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/asteroid_bazaar_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/steampunk_cathedral_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/steampunk_cathedral_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/steampunk_cathedral_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/postapocalyptic_mall_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/postapocalyptic_mall_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/postapocalyptic_mall_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/underwater_dome_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/underwater_dome_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/underwater_dome_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/orbital_habitat_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/orbital_habitat_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/orbital_habitat_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/solarpunk_farm_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/solarpunk_farm_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/solarpunk_farm_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/server_cathedral_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/server_cathedral_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/server_cathedral_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/zerogravity_chapel_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/zerogravity_chapel_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/zerogravity_chapel_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/giger_corridor_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/giger_corridor_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/giger_corridor_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/torii_corridor_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/torii_corridor_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/torii_corridor_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/grand_mosque_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/grand_mosque_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/grand_mosque_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/tibetan_library_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/tibetan_library_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/tibetan_library_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/speakeasy_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/speakeasy_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/speakeasy_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/scriptorium_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/scriptorium_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/scriptorium_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/seance_parlor_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/seance_parlor_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/seance_parlor_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/funhouse_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/funhouse_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/funhouse_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/colosseum_hypogeum_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/colosseum_hypogeum_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/colosseum_hypogeum_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/railway_terminal_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/railway_terminal_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/railway_terminal_s2.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pastel_hotel_s0.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pastel_hotel_s1.yaml"
"/home/a.schnepf/phd/SphericalDreamer/configs/rebuttal/diversity/cfgs/pastel_hotel_s2.yaml"
)


# Run experiments
for config in "${configs_p1[@]}"; do
    echo "🚀 Running experiment with config: $config"
    bash dream.sh $config

    if [ $? -ne 0 ]; then
        echo "❌ Experiment with config $config failed."
    fi

    echo "✅ Experiment with config $config completed successfully."
done

echo "🎉 All experiments completed successfully."