expname: futuristic_datacenter_2
load_phase1a_from: null
load_phase1b_from: null
load_phase2a_from: null
load_phase2b_from: null
load_phase2c_from: null
load_phase3_from: null
num_dreams: 20
prompt: A futuristic data center interior dominated by matte black and dark gray server
  racks, interlaced with glowing blue, green, and magenta cables under cool white
  overhead lighting.
save_dir: OUTPUTS/SphericalDreamerRecurse/_exp4_1a_only/
